export interface LearningStep {
  title: string;
  model: string;
  prediction: string;
  steps: string[];
  evidence: string;
}
export const learning: Record<number, LearningStep> = {
  1: { title: "Explain a blocked connection", model: "One light drone · kitchen block · flight time only", prediction: "Which candidate connection crosses a building? Can legal endpoints still form an illegal edge?", steps: ["Choose a connection and locate its endpoints and crossed building on the map.", "Compare the available legal routes to #03. Add their edge times before checking the route total.", "Write the task phases, including delivery and the return to the kitchen."], evidence: "Name the rejected connection and building. Explain why a route, a timed flight and a complete delivery task are different objects." },
  2: { title: "Trace the frontier", model: "One light drone · kitchen to #03 · non-negative edge times", prediction: "When may Dijkstra stop: when #03 is first discovered, or when its best entry is popped?", steps: ["Save the default result as your baseline, then step from the start.", "For each pop, predict the next OPEN row and record every improved parent.", "Switch to the straight-line heuristic and compare cost and expansions under the same graph."], evidence: "Record cost, expansions and one relaxation. Explain the stopping condition and why fewer expansions alone do not prove a correct answer." },
  3: { title: "Find the lost improvement", model: "Symbolic S–A–B–G graph · directed costs · no energy constraint", prediction: "The heuristic never overestimates. With reopening off, will the answer cost 4 or 5?", steps: ["Save the result with reopening off. Step until B finds a cheaper route to A.", "Turn reopening on; compare the path and the row where A is reopened.", "Set h = 0 and check that both the graph labels and the trace change. Explain the inconsistent edge."], evidence: "Identify B→A, compare h(B) with cost(B,A)+h(A), and explain why admissibility alone did not rescue the closed-node implementation." },
  4: { title: "Keep a route that can return", model: "Order #07 · full round trip · payload, service, energy and reserve", prediction: "Can the fastest route finish delivery and return within the light drone's usable battery?", steps: ["Compare the ridge and contour routes. Locate the kitchen, summit and the climb in the elevation profile.", "Save the full-label result; select Time only in the dominance slot and run and identify the feasible route it removes.", "Change to the heavy drone and explain why the feasibility judgement changes. Compare runs only within the same drone type."], evidence: "Record full-trip seconds, kJ and the usable budget. Explain why a faster label cannot dominate a slower one that uses less energy." },
  5: { title: "Choose the objective before the sequence", model: "Orders #01–#06 · one light drone · static trips · no shared charging", prediction: "Will FIFO and earliest deadline differ in lateness, final return time, or both?", steps: ["Save FIFO as your baseline and inspect the first two departure and delivery times.", "Switch to earliest deadline and compare the objective terms in their declared order.", "Enter your own permutation of #01–#06. Predict where waiting for an unready order affects the remaining tasks."], evidence: "Record both objective tuples. On this canonical case the preset strategies have zero lateness; explain which secondary term separates them." },
  6: { title: "Measure the gap after local search", model: "Editable six-job counterexample · 15 pair swaps · 720 permutations", prediction: "Will swaps reach the exact optimum on these six orders? What evidence would justify either answer?", steps: ["Save the swap result and inspect each accepted move.", "Run all 720 permutations and compare the objective, including ties.", "Switch to the canonical flight case to compare its zero gap with the symbolic counterexample. Keep the models separate."], evidence: "Report the observed exact gap and the stopping condition. A zero gap on this case does not prove that swaps are optimal on every instance." },
  7: { title: "Match an order to a capable drone", model: "Orders #01–#09 and #20 · three light drones or the five-drone mixed fleet", prediction: "What makes #20 impossible for a light drone, before schedule quality is considered?", steps: ["Move #20 onto a light drone, run and inspect its payload rejection.", "Move #20 back to a heavy drone and recompute the complete plan.", "Keep the fleet fixed and compare equal counts with earliest completion. Explain one assignment using the predicted completion costs."], evidence: "Separate a capability constraint from an efficiency choice. Changing fleet size and type together is not a controlled comparison of type alone." },
  8: { title: "Trace the charging queue", model: "Ten orders · editable assignment · two shared charging pads", prediction: "Which drone will have to wait for a pad, and how will that delay its next task?", steps: ["Select the two-drone, one-pad case first, then return to the ten-order case and save a baseline.", "Find a task with charging wait. Calculate its request time from landing plus turnaround.", "Move an order on the assignment board and run; trace the next task of both affected drones."], evidence: "Name the request time, charge start and next departure. Distinguish ground waiting at the kitchen from energy-consuming hover." },
  9: { title: "Resolve five seconds of shared airspace", model: "A to #13 · B returning · corridor capacity one · seconds after A's take-off", prediction: "B holds [87,112) and A wants [107,132). How long must A wait, and where?", steps: ["Save both-depart as the baseline and mark the overlap on the two occupancy lanes.", "Choose B first. Verify A enters exactly when B leaves and explain the half-open interval.", "Choose the detour. Compare A's arrival, hover and energy without changing the objective after the run."], evidence: "Record the conflict interval, waiting point and the two alternatives. The map shows where; the occupancy lanes show when." },
  10: { title: "Change who plans first", model: "Two complete tasks · fixed corridor reservations · space-time search", prediction: "Will the second drone wait on the ground, hover at the corridor, or take another route?", steps: ["Save A-first, then switch the priority to B-first.", "Inspect both directions of corridor occupancy and each drone's ground wait.", "Write why (place, phase, time) is necessary and why a fixed priority may miss a better joint plan."], evidence: "Report the priority, waits and resource intervals. Separate a plan against existing reservations from a global fleet optimum." },
  11: { title: "Trace feedback into the schedule", model: "Twenty orders · compare independent, reserved and revised assignments", prediction: "Can making routes conflict-free also make the original assignment late?", steps: ["Save the independent result and identify any resource violation.", "Choose reserved routes and locate the new waits and lateness.", "Choose bounded feedback, run the actual search and inspect an accepted migration and its recomputed waits."], evidence: "Name the assignment change and the resulting waits and objective. State the candidate budget. A budget stop does not prove a local or global optimum." },
  12: { title: "Audit one delivery from start to return", model: "All twenty orders · fixed reference assignment · charging and corridor enabled", prediction: "For #07, what limits departure: order readiness, the previous task, or charging?", steps: ["Select #07, then #13 and #20. Follow each outbound and return path on the map.", "For one order, match its ready, take-off, delivery and landing times to the previous task of its drone.", "Export the experiment record and state what the reference run demonstrates, and which unseen inputs it does not test."], evidence: "Give a complete causal account of one order, plus on-time count and the model limits. A successful reference run is evidence about that run." },
};
export const stages = [
  { start: 1, end: 3, title: "Find a route", outcome: "Model legal edges, trace Dijkstra, and explain A*." },
  { start: 4, end: 4, title: "Return within budget", outcome: "Keep time and energy labels for a complete delivery." },
  { start: 5, end: 6, title: "Order the tasks", outcome: "Declare an objective and test local improvement." },
  { start: 7, end: 8, title: "Divide the work", outcome: "Assign capable drones and share the charging pads." },
  { start: 9, end: 12, title: "Fly together", outcome: "Reserve shared airspace and feed delays back into the plan." },
];
